name:                surreal
version:             0.1.0.0
#github:              "juliagracedefoor/surreal"
license:             BSD3
author:              "Julia DeFoor"
maintainer:          "juliagracedefoor@gmail.com"
copyright:           "Julia DeFoor"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README.md for info about this package

dependencies:
- base >= 4.7 && < 5
- containers

library:
  source-dirs: src
